CREATE TABLE "audit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action" varchar(50),
	"audit_data" jsonb,
	"audit_by" uuid,
	"audit_on" timestamp,
	"audit_status" varchar(10),
	"audit_error" jsonb,
	CONSTRAINT "audit_status_constraints" CHECK ("audit"."audit_status" in ('success', 'failure', 'pending'))
);
--> statement-breakpoint
CREATE TABLE "cart_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cart_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer,
	"cart_id" integer,
	"quantity" integer DEFAULT 0,
	"discount" numeric DEFAULT '0.0',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT null,
	"deleted_at" timestamp DEFAULT null,
	CONSTRAINT "cart_items_quantity_constraints" CHECK ("cart_items"."quantity" >= 0),
	CONSTRAINT "cart_items_discount_constraints" CHECK ("cart_items"."discount" >= 0)
);
--> statement-breakpoint
CREATE TABLE "cart" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"order_id" integer NOT NULL,
	"total_amount" numeric DEFAULT '0.0',
	"total_discount" numeric DEFAULT '0.0',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT null,
	"deleted_at" timestamp DEFAULT null,
	CONSTRAINT "cart_total_amount_constraints" CHECK ("cart"."total_amount" >= 0),
	CONSTRAINT "cart_total_discount_constraints" CHECK ("cart"."total_discount" >= 0)
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(250) NOT NULL,
	"image" text DEFAULT null,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT null,
	"deleted_at" timestamp DEFAULT null,
	CONSTRAINT "categories_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_id" uuid NOT NULL,
	"cart_id" integer NOT NULL,
	"payment_method_type" varchar DEFAULT 'cash',
	"status" varchar DEFAULT 'pending',
	"shipping_at" timestamp,
	"shipping_address" varchar(250),
	"shipping_price" numeric DEFAULT '0.0',
	"total_price" numeric DEFAULT '0.0',
	"is_paid" boolean DEFAULT false,
	"paid_at" timestamp DEFAULT null,
	"created_at" timestamp DEFAULT now(),
	"created_by" uuid DEFAULT null,
	"updated_at" timestamp DEFAULT null,
	"updated_by" uuid DEFAULT null,
	"deleted_at" timestamp DEFAULT null,
	"deleted_by" uuid DEFAULT null,
	CONSTRAINT "orders_shipping_price_constraints" CHECK ("orders"."shipping_price" >= 0),
	CONSTRAINT "orders_total_price_constraints" CHECK ("orders"."total_price" >= 0)
);
--> statement-breakpoint
CREATE TABLE "products_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "products_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT null,
	"deleted_at" timestamp DEFAULT null
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category_id" integer NOT NULL,
	"title" varchar(50) NOT NULL,
	"description" text DEFAULT null,
	"quantity" integer DEFAULT 0,
	"cover_image" text DEFAULT null,
	"price" numeric DEFAULT '0.0',
	"discount" numeric DEFAULT '0.0',
	"rating_average" numeric DEFAULT '0.0',
	"rating_quantity" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"created_by" uuid DEFAULT null,
	"updated_at" timestamp DEFAULT null,
	"updated_by" uuid DEFAULT null,
	"deleted_at" timestamp DEFAULT null,
	"deleted_by" uuid DEFAULT null,
	CONSTRAINT "products_quantity_constraints" CHECK ("products"."quantity" >= 0),
	CONSTRAINT "products_price_constraints" CHECK ("products"."price" >= 0),
	CONSTRAINT "products_discount_constraints" CHECK ("products"."discount" >= 0),
	CONSTRAINT "products_rating_average_constraints" CHECK ("products"."rating_average" BETWEEN 0 AND 5),
	CONSTRAINT "products_rating_quantity_constraints" CHECK ("products"."rating_quantity" >=0)
);
--> statement-breakpoint
CREATE TABLE "reviews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid,
	"product_id" integer,
	"content" text DEFAULT null,
	"rate" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"created_by" uuid DEFAULT null,
	"updated_at" timestamp DEFAULT null,
	"updated_by" uuid DEFAULT null,
	"deleted_at" timestamp DEFAULT null,
	"deleted_by" uuid DEFAULT null,
	CONSTRAINT "reviews_rate_constraints" CHECK ("reviews"."rate" BETWEEN 1 AND 5)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"first_name" varchar(50) NOT NULL,
	"last_name" varchar(50) NOT NULL,
	"email" varchar(255) NOT NULL,
	"username" varchar(255) NOT NULL,
	"password_hash" text NOT NULL,
	"role" varchar DEFAULT 'user',
	"avatar" text DEFAULT null,
	"age" integer,
	"phone_number" varchar(11),
	"address" varchar(255) DEFAULT 'Egypt',
	"is_active" boolean DEFAULT false,
	"gender" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT null,
	"deleted_at" timestamp DEFAULT null,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_age_constraints" CHECK ("users"."age" >= 18),
	CONSTRAINT "users_phone_number_constraints" CHECK ("users"."phone_number" ~ '^(01)[0-9]{9}$')
);
--> statement-breakpoint
ALTER TABLE "audit" ADD CONSTRAINT "audit_audit_by_fk" FOREIGN KEY ("audit_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_cart_id_fk" FOREIGN KEY ("cart_id") REFERENCES "public"."cart"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart" ADD CONSTRAINT "cart_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart" ADD CONSTRAINT "cart_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "order_owner_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "order_cart_id_fk" FOREIGN KEY ("cart_id") REFERENCES "public"."cart"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "order_created_by_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "order_updated_by_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "order_deleted_by_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products_images" ADD CONSTRAINT "products_images_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "product_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "product_created_by_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "product_updated_by_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "product_deleted_by_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "review_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "review_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "review_created_by_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "review_updated_by_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "review_deleted_by_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_on_idx" ON "audit" USING btree ("audit_on");--> statement-breakpoint
CREATE INDEX "audit_by_idx" ON "audit" USING btree ("audit_by");--> statement-breakpoint
CREATE INDEX "categories_name_idx" ON "categories" USING btree ("name");--> statement-breakpoint
CREATE INDEX "orders_payment_method_type" ON "orders" USING btree ("payment_method_type");--> statement-breakpoint
CREATE INDEX "orders_status" ON "orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "products_title_idx" ON "products" USING btree ("title");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_username_idx" ON "users" USING btree ("username");--> statement-breakpoint
CREATE INDEX "users_user_role_idx" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "users_is_active_idx" ON "users" USING btree ("is_active");